language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
# command to run tests
script:
  - pytest --cov=. --cov-report term-missing
  - codecov
