[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
line_length = 120
include_trailing_comma = true

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120
disable = "C0114, R1705, C0103, C0415, R1710"

[tool.pytest.ini_options]
addopts = "-v --cov=. --cov-report term-missing --cov-fail-under 96"
python_files = "tests/test_*.py"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]
