name: Add new GitHub issue to "Backlog" Project

on:
  issues:
    types: [opened]

jobs:
  add-new-issues-to-project-column:

    runs-on: ubuntu-latest

    steps:
    - name: Add issues to Backlog
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.DEMOCRITUS_ISSUE_TO_BACKLOG_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/orgs/democritus-project/projects/8
        GITHUB_PROJECT_COLUMN_NAME: To do
